module(
    name = "rules_wasm",
    version = "2.3.0",
    # Since some external repositories use patches,
    # we need to specify `7.2.1` as the minimum compatible Bazel version.
    # https://github.com/bazelbuild/bazel-central-registry/blob/310e56d7b185c997d5a862775ce30116206b9ad1/tools/bcr_validation.py#L668-L669
    bazel_compatibility = [">=7.2.1"],
)

bazel_dep(name = "buildifier_prebuilt", version = "8.5.1.3", dev_dependency = True, repo_name = "buildtools")

bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "gazelle", version = "0.51.3")
bazel_dep(name = "jq.bzl", version = "0.6.1")
bazel_dep(name = "package_metadata", version = "0.0.13")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_go", version = "0.61.1", repo_name = "io_bazel_rules_go")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_rust", version = "0.70.0")
bazel_dep(name = "rules_shell", version = "0.8.0")

# The example module (which contains basic tests)
# is itself referenced by tests in the main module,
# which verify that some example tests are running properly.
bazel_dep(name = "example", dev_dependency = True)
local_path_override(
    module_name = "example",
    path = "example",
)

# Supported execution platforms for pre-built binaries.
# TODO: Figure out how to dedupe this list with `private.bzl`.
execution_platforms = [
    "aarch64-linux",
    "aarch64-macos",
    "x86_64-linux",
    "x86_64-macos",
]

# https://github.com/WebAssembly/binaryen/releases
binaryen_version = "131"

# https://pkg.go.dev/go.bytecodealliance.org/cm?tab=versions
go_cm_version = "0.3.0"

# https://github.com/tinygo-org/tinygo/releases
tinygo_version = "0.41.1"

# https://github.com/bytecodealliance/wac/releases
wac_version = "0.10.1"

# ATTOW TinyGo only supports version `0.2.0`:
# https://github.com/WebAssembly/WASI/releases
wasi_version = "0.2.0"

# https://github.com/WebAssembly/wasi-sdk/releases
wasi_sdk_version = "33"

# https://github.com/bytecodealliance/wasmtime/releases
wasmtime_version = "47.0.2"

# https://github.com/bytecodealliance/wasm-tools/releases
wasm_tools_version = "1.254.0"

# https://github.com/bytecodealliance/wit-bindgen/releases
wit_bindgen_version = "0.59.0"

# https://github.com/bytecodealliance/go-modules/releases
wit_bindgen_go_version = "0.7.0"

jq = use_extension("@jq.bzl//jq:extensions.bzl", "toolchains")
use_repo(jq, "jq_toolchains")

# Rust setup: wit-bindgen-generated Rust files depend on the wit-bindgen crate.
crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.spec(
    package = "wit-bindgen",
    version = wit_bindgen_version,
)
crate.from_specs(
    name = "rules-wasm-crates",
    # Hardcode all supported Rust toolchains to make Cargo splicing more efficient.
    # https://github.com/bazelbuild/rules_rust/discussions/2259
    supported_platform_triples = [
        "aarch64-unknown-linux-gnu",
        "aarch64-apple-darwin",
        "wasm32-wasip2",
        "x86_64-unknown-linux-gnu",
        "x86_64-apple-darwin",
    ],
)
use_repo(crate, "rules-wasm-crates")

# Manually download prebuilt binaries for various dependencies:

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

[http_archive(
    name = "binaryen.{}".format(exe_platform),
    build_file_content = """
alias(
    name = "wasm-opt",
    actual = "binaryen-version_{version}/bin/wasm-opt",
    visibility = ["//visibility:public"],
)
""".format(version = binaryen_version),
    integrity = {
        "aarch64-linux": "sha384-3LKBz3VZ5x8lW699u74oAxbjjkNY8NBgD/IQl/ioTUM/L9oP5/JMkhEDUxL7njc2",
        "aarch64-macos": "sha384-uQY1QWXp/6dlCdxRMAg9DOhmKqQsfRMJOvjuGyrEnSQyXaR49EKO+Fc6xGB0t/xb",
        "x86_64-linux": "sha384-zUAnBb3a5P/iQBjAskKg2d1/Uw53dF+r7+j3wFqPN+vfZn5fXLLSjZNHh3GICrWh",
        "x86_64-macos": "sha384-ELUja8M3IsokKXLBJaqmKs3MP2GEL+V2o4fwhIUam3EbBJhSijJodeEoTI0euW9D",
    }[exe_platform],
    url = "https://github.com/WebAssembly/binaryen/releases/download/version_{version}/binaryen-version_{version}-{platform}.tar.gz".format(
        platform = {
            "aarch64-linux": "aarch64-linux",
            "aarch64-macos": "arm64-macos",
            "x86_64-linux": "x86_64-linux",
            "x86_64-macos": "x86_64-macos",
        }[exe_platform],
        version = binaryen_version,
    ),
) for exe_platform in execution_platforms]

wac_platforms = {
    "aarch64-linux": "aarch64-unknown-linux-musl",
    "aarch64-macos": "aarch64-apple-darwin",
    "x86_64-linux": "x86_64-unknown-linux-musl",
    "x86_64-macos": "x86_64-apple-darwin",
}

[http_file(
    name = "wac.{}".format(exe_platform),
    executable = True,
    integrity = {
        "aarch64-linux": "sha384-hLvOt52gPFVyxhV1dYhBtqjLHpUeoqEafWiVu6fP0tAoRxJ6pwSZrOh7YtWpeTWh",
        "aarch64-macos": "sha384-1ts4aVXLCdDrOwYPRbD35ctXek1yR3lSkXzFpa1/28jWOSG/Qmuz2GGvwfgRJvwP",
        "x86_64-linux": "sha384-LoV64lDC18wFWEfMQcG98aabyfZEIHW529TkpRUwo/BwUkYz5b3tATS84dxmja3B",
        "x86_64-macos": "sha384-QuSqgxc7H0pNhZxr6vc6nfgYfYkuiQb3tYXj+JghMXiDPPGm0jdZvzHi2NkwLUq1",
    }[exe_platform],
    url = "https://github.com/bytecodealliance/wac/releases/download/v{version}/wac-cli-{platform}".format(
        # WAC uses non-canonical platform strings in the URLs:
        platform = wac_platforms[exe_platform],
        version = wac_version,
    ),
) for exe_platform in execution_platforms]

http_archive(
    name = "wasi",
    build_file_content = """
load(":wasm.bzl", "wasi_packages")

[filegroup(
    name = package,
    srcs = glob(["WASI-{version}/preview2/" + package + "/*.wit"]),
    visibility = ["//visibility:public"],
) for package in wasi_packages.keys()]
""".format(version = wasi_version),
    integrity = "sha384-k5+dIIcSf9AtW/dpJ4wHglf9GCs0OZw5I90Lkd74RZ/X8PMv0Cx9WKFPsTFPCV9H",
    # Ideally there would be something like `remote_file_urls` for local files
    # so we can eliminate this redundant patch file
    # and instead just copy `wasm.bzl` into the remote repo:
    # https://github.com/bazelbuild/bazel/issues/24499.
    patches = ["//wasm:wasi.patch"],
    url = "https://github.com/WebAssembly/WASI/archive/refs/tags/v{version}.tar.gz".format(version = wasi_version),
)

wasi_sdk_platforms = {
    "aarch64-linux": "arm64-linux",
    "aarch64-macos": "arm64-macos",
    "x86_64-linux": "x86_64-linux",
    "x86_64-macos": "x86_64-macos",
}

[http_archive(
    name = "wasi-sdk.{}".format(exe_platform),
    # Note: these are symlinks within the HTTP archive:
    # - clang -> clang-19
    # - ar -> llvm-ar
    # - nm -> llvm-nm
    # - objdump -> llvm-objdump
    # - strip -> llvm-objcopy
    build_file_content = """
load("@bazel_skylib//rules/directory:directory.bzl", "directory")
load("@bazel_skylib//rules/directory:subdirectory.bzl", "subdirectory")

package(default_visibility=["//visibility:public"])

alias(name = "clang", actual = "wasi-sdk-{version}.0-{platform}/bin/clang")
alias(name = "wasm-component-ld", actual = "wasi-sdk-{version}.0-{platform}/bin/wasm-component-ld")
alias(name = "ar", actual = "wasi-sdk-{version}.0-{platform}/bin/ar")
alias(name = "nm", actual = "wasi-sdk-{version}.0-{platform}/bin/nm")
alias(name = "objdump", actual = "wasi-sdk-{version}.0-{platform}/bin/objdump")
alias(name = "strip", actual = "wasi-sdk-{version}.0-{platform}/bin/strip")

directory(
    name = "lib",
    srcs = glob(["wasi-sdk-{version}.0-{platform}/lib/**"]),
)
subdirectory(
    name = "include",
    parent = ":lib",
    path = "clang/19/include",
)
""".format(
        platform = wasi_sdk_platforms[exe_platform],
        version = wasi_sdk_version,
    ),
    integrity = {
        "aarch64-linux": "sha384-P+Nl2RmQt3g7HDhe5FRT2iuwWLazvtwJBNj0Rl60Mk4kewD2ZuSK3vJar6EMZtUT",
        "aarch64-macos": "sha384-WYIfedFxIgp+CcnGQaIkJtWzCiSkRlwercHS326fkJw/SJl3nnRitxJGAe+earce",
        "x86_64-linux": "sha384-eTDjfKraDtLIN6VLUg+2C0H+el2YZi3cL3Nm6SzTv0Ne/MmXJEI1rwa1OAlXRedG",
        "x86_64-macos": "sha384-SGt5X30gbufj7pyN/vHRBBsKaZuQP+N6NCNN/fi0t3SPEo1lyVVpZmxwkjD5/8Zs",
    }[exe_platform],
    url = "https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-{version}/wasi-sdk-{version}.0-{platform}.tar.gz".format(
        platform = wasi_sdk_platforms[exe_platform],
        version = wasi_sdk_version,
    ),
) for exe_platform in execution_platforms]

[http_archive(
    name = "wasmtime.{}".format(exe_platform),
    build_file_content = """
alias(
    name = "wasmtime",
    actual = "wasmtime-v{version}-{platform}/wasmtime",
    visibility = ["//visibility:public"],
)
""".format(
        platform = exe_platform,
        version = wasmtime_version,
    ),
    integrity = {
        "aarch64-linux": "sha384-SH7Z2nFqe0ib4I6C9XVH02DsADMaex7m9vDM3Z1NOoDianbRH8m8vjZrHgRGq3jK",
        "aarch64-macos": "sha384-qgnw6LSMZvUxzEI/0liBLRJ2f0NL86YNObsnjK3uiaJYAePOAFMIKfytoWOpKWG0",
        "x86_64-linux": "sha384-Ga/taM7R0rFqbgdCG2V6DVgc2eGBhuKpHA6DzDXiRkMgHRdVVD1zuIYil43dTb9Y",
        "x86_64-macos": "sha384-XffYyF94d13m77KP4u0GyrdFeftSCGNv9EG5g53ExAdokA7Lh2mbLv7f2dA80Vfw",
    }[exe_platform],
    url = "https://github.com/bytecodealliance/wasmtime/releases/download/v{version}/wasmtime-v{version}-{platform}.tar.xz".format(
        platform = exe_platform,
        version = wasmtime_version,
    ),
) for exe_platform in execution_platforms]

[http_archive(
    name = "wasm-tools.{}".format(exe_platform),
    build_file_content = """
alias(
    name = "wasm-tools",
    actual = "wasm-tools-{version}-{platform}/wasm-tools",
    visibility = ["//visibility:public"],
)
""".format(
        platform = exe_platform,
        version = wasm_tools_version,
    ),
    integrity = {
        "aarch64-linux": "sha384-sYZFVoHphZaD74zrG5pHBMfQCzg7Zy1eZpjHg1lZzup/AF9SvLC/hkmWArRR/h2V",
        "aarch64-macos": "sha384-t3+5Ug6lg/X/OSxE4IPvZfJS1O6jFpLWQq0dS+pOXK43rTMbAxwpdnsav7ESYju0",
        "x86_64-linux": "sha384-TzrQbHYV+Aelkdk+qgR8YTNWC9WmvGhTvhlOFgeB9meGbXT9oKQwKZ/1f42zWE1p",
        "x86_64-macos": "sha384-TsGk4dYmNujbEMSmLCpbyN/Ug9JDiLCagXQpGVg6AKRxgIe7XZQzAl/Wr8LvGlZY",
    }[exe_platform],
    url = "https://github.com/bytecodealliance/wasm-tools/releases/download/v{version}/wasm-tools-{version}-{platform}.tar.gz".format(
        platform = exe_platform,
        version = wasm_tools_version,
    ),
) for exe_platform in execution_platforms]

[http_archive(
    name = "wit-bindgen.{}".format(exe_platform),
    build_file_content = """
alias(
    name = "wit-bindgen",
    actual = "wit-bindgen-{version}-{platform}/wit-bindgen",
    visibility = ["//visibility:public"],
)
""".format(
        platform = exe_platform,
        version = wit_bindgen_version,
    ),
    integrity = {
        "aarch64-linux": "sha384-T9vMd4rakwnOyaxPqHihYloB1w5XIAwlqOQ4IB9mKnjLt4WfOFl4th4f6ACJJGSe",
        "aarch64-macos": "sha384-JvSVuVXdEDIh4RJJBjxHyrb8muN3ZlEMHDjWGXNcer0d9DED9OCKX4ohmuanQhGe",
        "x86_64-linux": "sha384-0SJ9mSCHG2jvz3YpTPNN/tEYSd/I/k4pX/3xjvdrDGNSy+pOBwRqVCBjeNgZ8VRm",
        "x86_64-macos": "sha384-K3CQS8bS8hjsKRCSnMnY8ZQOmKbsjjPI0ydHtPgKtmJ4zKYPILv7VaAFX9via6YC",
    }[exe_platform],
    url = "https://github.com/bytecodealliance/wit-bindgen/releases/download/v{version}/wit-bindgen-{version}-{platform}.tar.gz".format(
        platform = exe_platform,
        version = wit_bindgen_version,
    ),
) for exe_platform in execution_platforms]

[http_archive(
    name = "tinygo.{}".format(exe_platform),
    build_file_content = """
alias(
    name = "tinygo",
    actual = "tinygo/bin/tinygo",
    visibility = ["//visibility:public"],
)
""",
    integrity = {
        "aarch64-linux": "sha384-hFL7jW7RgttffkTQijoGqlFFdVMQHv5GKWtKfitp8gnOFaDBuIsnCu3mygeiZdH+",
        "aarch64-macos": "sha384-OJQemsYsR6Lx8UeayRLNLwIbDd8+V2XFuc9cgM4KzfPFkmrPHgKe4Qe6BwiYewNV",
        "x86_64-linux": "sha384-wsXo2bmFXByTKOQlNIgv1utXs+9RcoyDVJDZFLUj3PCsxV/ztkyKeJqafDStjPuC",
        "x86_64-macos": "sha384-B9oDxyaapP89L+36Ixemq/kjCPmaePweyMkSynvadFXrf2a7SpIj0J0rizZ5StSZ",
    }[exe_platform],
    url = "https://github.com/tinygo-org/tinygo/releases/download/v{version}/tinygo{version}.{platform}.tar.gz".format(
        platform = {
            "aarch64-linux": "linux-arm64",
            "aarch64-macos": "darwin-arm64",
            "x86_64-linux": "linux-amd64",
            "x86_64-macos": "darwin-amd64",
        }[exe_platform],
        version = tinygo_version,
    ),
) for exe_platform in execution_platforms]

[http_archive(
    name = "wit-bindgen-go.{}".format(exe_platform),
    build_file_content = """
exports_files(
    ["wit-bindgen-go"],
    visibility = ["//visibility:public"],
)
""",
    integrity = {
        "aarch64-linux": "sha384-cbNymuUTUpvyb0jVrN+Fy97NgFYmGyJQ+Ml7QyMa98G4KMKAi/Cbp/nRY/xGhvZX",
        "aarch64-macos": "sha384-Yn43/bbLp4HKX2oz85ESWZOJgsa0La30Vda+SabuowxtS4604R+9h0ks1n1J0xGV",
        "x86_64-linux": "sha384-a5R9jT7HdEHxManvsn8qhyP0Qma/kFousmmPVy4j+QHLat0eDh6aTfyXq1W6KyUd",
        "x86_64-macos": "sha384-WmFNc+tWLOCe8zYuYBcQ/99ffOensY/FN1XmijQpVIWSBqz/KSIsPgDitVx2LJJF",
    }[exe_platform],
    url = "https://github.com/bytecodealliance/go-modules/releases/download/v{version}/wit-bindgen-go-{platform}.tgz".format(
        platform = {
            "aarch64-linux": "linux-arm64",
            "aarch64-macos": "darwin-arm64",
            "x86_64-linux": "linux-amd64",
            "x86_64-macos": "darwin-amd64",
        }[exe_platform],
        version = wit_bindgen_go_version,
    ),
) for exe_platform in execution_platforms]

# Temporary crutch until we can build against wasip2 directly.
http_file(
    name = "wasi-snapshot-preview1-reactor",
    integrity = "sha384-xQqif8aps3a8DLmlo2Q24T5G7dic8qnjXEoqyqhR1EpTLlVHp7cT/i/cgwT2UnW4",
    url = "https://github.com/bytecodealliance/wasmtime/releases/download/v{version}/wasi_snapshot_preview1.reactor.wasm".format(version = wasmtime_version),
)

go_repository = use_repo_rule("@gazelle//:deps.bzl", "go_repository")

# The only dependency for generated Go bindings.
go_repository(
    name = "go-component-model-utility",
    importpath = "go.bytecodealliance.org/cm",
    # The patch expose the `go.mod` file
    # as well as the Gazelle-generated package info.
    patches = ["//go:cm.patch"],
    sum = "h1:VhV+4vjZPUGCozCg9+up+FNL3YU6XR+XKghk7kQ0vFc=",
    version = "v{}".format(go_cm_version),
)

register_toolchains("//:wasm32-wasi-toolchain")
