name: Release
on:
  release:
    types: ['released']

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package
        # Include all tracked top-level files and folders in the release archive.
        run: git ls-tree --name-only HEAD | xargs tar czf rules_wasm-${{ github.ref_name }}.tar.gz
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          path: rules_wasm-${{ github.ref_name }}.tar.gz
