name: Release
on:
  release:
    types: ['released']
permissions:
  # Necessary to upload a release asset:
  contents: write
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Release Archive
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # `ASSET_NAME` looks like `rules_wasm-v1.2.3.tar.gz`.
          ASSET_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz
        run: |
          # Extract the Bazel module version from `MODULE.bazel` (distinct from the GitHub release tag).
          # `ROOT_DIRECTORY` looks like `rules_wasm-1.2.3.tar.gz`.
          export ROOT_DIRECTORY="${{ github.event.repository.name }}-$(bazel mod explain --output json '<root>' | jq --raw-output .version)"

          # Add all Git-tracked files to a TAR archive.
          # Use `--transform` to insert a single parent directory inside the archive
          # because the BCR publishing app seems to like that.
          # https://github.com/bazel-contrib/publish-to-bcr
          git ls-tree --name-only HEAD | xargs tar --transform "s,^,${ROOT_DIRECTORY}/," -czf ${ASSET_NAME}
          gh release upload ${{ github.ref_name }} ${ASSET_NAME}
