name: Release
on:
  release:
    types: ['released']

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Release Archive
        run: |
          git ls-tree --name-only HEAD | xargs tar czf ${ASSET_NAME}
          gh release upload ${{ github.event.release.tag_name }} ${ASSET_NAME}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSET_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz
