name: Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bazel
        # https://bazel.build/install/ubuntu#install-on-ubuntu
        run: >
          sudo apt update
          && sudo apt install -y apt-transport-https curl gnupg
          && curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          && sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          && sudo apt update
          && sudo apt install -y bazel
      - name: Build Everything
        run: bazel build //...
      - name: Run Tests
        run: bazel test //...
      - name: Upload Log
        uses: actions/upload-artifact@v4
        with:
          name: bazel-testlogs
          path: bazel-testlogs/
